const translations = {
    bg: {
        // Глобални елементи
        nav_home: "Начало",
        nav_kitchen: "Кухня",
        nav_bedroom: "Спалня",
        nav_living: "Всекидневна",
        nav_bathroom: "Баня",
        nav_kids: "Детска стая",
        nav_contact: "Контакти",
        btn_header_quote: "Поискайте оферта",
        
        footer_company: "Custom Furnitures",
        footer_office: "Офис (София): ж.к. Младост 2, бл. 225, 1799 София, България",
        footer_prod: "Производство (Видин): Западна складова зона, 3700 Видин, България",
        footer_maps_btn: "Упътване в Google Maps",
        footer_phone: "Тел: 00359878359358",
        footer_email: "info@customfurnitures.com",
        footer_news_heading: "Абонирайте се за нашия бюлетин",
        footer_news_btn: "Абониране",
        footer_copyright: "Авторско право 2026, Всички права запазени",

        // Начална страница
        hero_title: "Създаваме модерни мебели с изчистени линии и максимална функционалност.",
        hero_subtitle: "Проектираме интелигентни решения за съхранение, които оптимизират всяко кътче от дома или офиса.",
        btn_hero: "Заявете консултация",
        btn_hero_call: "Обадете се",
        
        benefit_1: "24 месеца гаранция",
        benefit_2: "Индивидуален 3D проект",
        benefit_3: "Премиум материали и обков",
        
        philosophy_text: "Не просто запълваме дупки в стената. Ние проектираме движението ви в кухнята или спалнята. Нашите дизайнери мислят за това къде ще е контактът, как ще се отварят вратичките и дали ще ви е удобно да достигате всичко",
        wave_tag: "Нашата<br>Философия",
        
        featured_heading: "Разгледайте нашите топ реализации",
        btn_view_project: "Разгледай проекта",
        
        cta_final: "Готови ли сте да трансформирате пространството си?",
        btn_contact_us: "Свържете се с нас",
        previews_heading: "Нашите проекти",
        btn_contact_write: "Пишете ни",
        partners_title: "Нулев компромис в качеството",
        partners_subtitle: "само най-добрите материали",

        // Страници на категории
        cat_kitchens: "Кухни по поръчка",
        cat_bedrooms: "Спални и легна",
        cat_kids_beds: "Детски легла",
        cat_living: "Всекидневни по поръчка",
        cat_living_desks: "Всекидневни и Бюра",
        cat_wardrobes: "Гардероби",
        cat_bathrooms: "Бани",
        cat_kids_rooms: "Детска стая по поръчка",
        footer_categories: "Категории",
        cat_intro: "Функционалност без компромис с дизайна. Разгледайте нашите реализации и почерпете вдъхновение за вашия дом.",
        cat_intro_bedrooms: "Вашето пространство за сън с комфорт и стил",
        cat_intro_living: "Разгледайте нашата колекция за всекидневни",
        cat_intro_kitchens: "Сърцето на вашия дом",
        cat_intro_bathrooms: "Дизайн и комфорт за вашата баня",
        cat_intro_kids: "Функционални и забавни решения за детската стая",
        cat_cta: "Обсъдете вашия проект с нас.",

        flourish_title: "Пространство за Живот<br>което Процъфтява",
        flourish_desc: "Открийте нашите премиум решения, които придават минималистичен вид на вашия дом с усещане за лукс.",

        transform_bg_text: "Готови ли сте<br>да промените<br>дома си?",
        transform_bottom_text: "Пишете ни<span style='margin-left: 3rem'>Или ни се обадете</span>",
        transform_cta_text: "Нека<br>Започнем",

        cb_marquee: "Естествени материали • Ежедневен живот • Форми • Естествени материали • Ежедневен живот • Форми • ",
        cb_text_1: "Ако се интересувате от нашите мебели, материали или текуща работа, приветстваме разговори за проекти.",
        cb_text_2: "За търговски, жилищни или комерсиални запитвания, моля, свържете се директно с нас.",
        cb_btn: "Свържете се с нас",

        mixed_title_1: "Тих растеж: Топъл дом, оформен от зеленина и нежни моменти",
        mixed_title_2: "Топли слоеве: Спокойно пространство за споделени моменти",
        tag_oriental: "Ориенталски",
        tag_natural: "Естествен",
        tag_family: "Семейство",
        tag_calm: "Спокойствие",
        tag_warm: "Топлина",
        tag_layered: "Наслоено",
        tag_dining: "Трапезария",
        view_case: "Вижте проекта",
        
        reviews_heading: "Както казват нашите клиенти за услугите ни",
        google_reviews_subtitle: "Въз основа на потвърдени отзиви в Google",
        review_upload_label: "Снимки към отзива (макс. 3)",
        review_upload_drag: "Привлачете снимки или кликнете за избор",
        btn_leave_review: "Оставете отзив",
        review_placeholder_1: "\"Изключително качество и внимание към детайла. Екипът беше изключително професионален от първоначалния 3D проект до финалния монтаж.\"",
        review_name_1: "Иван Петров",
        review_role_1: "София",
        review_placeholder_2: "\"Превърнаха кухнята ни в шедьовър. Функционалност и естетика в перфектен баланс.\"",
        review_name_2: "Мария Димитрова",
        review_role_2: "Пловдив",
        review_placeholder_3: "\"Силно препоръчвам! Гардеробът по поръчка пасва идеално и използваните материали са първокласни.\"",
        review_name_3: "Георги Тодоров",
        review_role_3: "Варна",
        review_placeholder_4: "\"Страхотна комуникация и безупречно изпълнение. Всекидневната ни изглежда сякаш е от списание.\"",
        review_name_4: "Елена Николова",
        review_role_4: "Бургас",
        
        footer_title: "Тих, Естествен, Смислен Живот",
        footer_desc: "Custom Furnitures е лайфстайл марка, създаваща естествени мебели за ежедневието.",
        footer_quick: "Бързи връзки",
        footer_home: "Начало",
        footer_product: "Нашите Продукти",
        footer_featured: "Избрани Проекти",
        footer_contact: "Контакти",
        footer_leave_review: "Оставете ни отзив",
        review_title: "Оставете Вашия отзив",
        review_subtitle: "Споделете Вашето мнение за нашите мебели и обслужване",
        review_form_name: "Вашето име",
        review_form_city: "Град",
        review_form_rating: "Рейтинг",
        review_form_text: "Вашият отзив",
        review_form_submit: "Изпрати отзив",
        review_success: "Благодарим Ви! Вашият отзив беше изпратен успешно.",
        review_back_home: "Към началната страница",
        footer_studio_title: "Нашето Студио",
        footer_studio_address: "ж.к. Младост 2, бл. 225, 1799 София<br>България",
        footer_legal: "Правна информация",
        footer_terms: "Общи условия",
        footer_privacy: "Политика за поверителност",

        // Страници на избрани проекти (Пример)
        case_title: "Премиум кухня с интегрирано LED осветление",
        case_challenge: "Предизвикателство: Усвояване на нестандартно пространство и оптимизиране на височината.",
        case_solution: "Решение: Изработка на мебели по индивидуален проект с безшевна интеграция на уредите и интелигентно разпределение.",
        case_materials: "Използвани материали: МДФ фурнир дъб, обков Blum, италиански лак",
        btn_case_inquire: "Запитай за подобен проект",

        // Страница Контакти
        contact_heading: "Свържете се с нас",
        contact_subheading: "Изпратете ни запитване и ние ще се свържем с вас, за да обсъдим детайлите по вашия проект.",
        form_name: "Име и Фамилия",
        form_phone: "Телефонен номер",
        form_email: "Имейл адрес",
        form_desc: "Опишете проекта си (тип помещение, размери, специфични изисквания)",
        form_file: "Прикачете файл (скица или снимка)",
        btn_form_submit: "Изпрати запитване",

        // Модал за проекти
        modal_btn_similar: "Поискай оферта за подобен проект",
        modal_btn_consult: "Поискай консултация",
        modal_desc_placeholder: "Кратко описание на проекта, включващо детайли за материалите и дизайна.",
        form_autofill: "Здравейте, имам интерес относно подобен проект на"
    },
    en: {
        // Global Elements
        nav_home: "Home",
        nav_kitchen: "Kitchen",
        nav_bedroom: "Bedroom",
        nav_living: "Living Room",
        nav_bathroom: "Bathroom",
        nav_kids: "Kids' Room",
        nav_contact: "Contacts",
        btn_header_quote: "Request a Quote",
        
        footer_company: "Custom Furnitures",
        footer_office: "Office (Sofia): Mladost 2, bl. 225, 1799 Sofia, Bulgaria",
        footer_prod: "Production (Vidin): West Storage Zone, 3700 Vidin, Bulgaria",
        footer_maps_btn: "Google Maps Directions",
        footer_phone: "Phone: 00359878359358",
        footer_email: "info@customfurnitures.com",
        footer_news_heading: "Sign up for our newsletter",
        footer_news_btn: "Enter",
        footer_copyright: "Copyright 2026, All Right Reserved",

        // Home Page
        hero_title: "We create modern furniture with clean lines and maximum functionality.",
        hero_subtitle: "We design smart storage solutions that optimize every corner of your home or office.",
        btn_hero: "Request a Consultation",
        btn_hero_call: "Call Us",
        
        benefit_1: "24-Month Warranty",
        benefit_2: "Free 3D Project",
        benefit_3: "Premium Materials & Hardware",
        
        philosophy_text: "We don't just fill holes in the wall. We design your movement in the kitchen or bedroom. Our designers think about where the outlet will be, how the doors will open, and whether it will be comfortable for you to reach everything.",
        wave_tag: "Our<br>Philosophy",
        
        featured_heading: "Explore Our Top Projects",
        btn_view_project: "View Project",
        
        cta_final: "Ready to transform your space?",
        btn_contact_us: "Contact Us",
        previews_heading: "Our Work",
        btn_contact_write: "Write to us",
        partners_title: "Zero Compromise in Quality",
        partners_subtitle: "Only the best materials",

        // Category Pages
        cat_kitchens: "Custom Kitchens",
        cat_bedrooms: "Bedrooms & Beds",
        cat_kids_beds: "Children's Beds",
        cat_living: "Custom Living Rooms",
        cat_living_desks: "Living Rooms & Desks",
        cat_wardrobes: "Wardrobes",
        cat_bathrooms: "Bathrooms",
        cat_kids_rooms: "Custom Kids' Room",
        footer_categories: "Categories",
        cat_intro: "Functionality without compromising design. Explore our realizations and get inspired for your home.",
        cat_intro_bedrooms: "Your Sleep Space with Comfort and Style",
        cat_intro_living: "Browse Our Living Room Collection",
        cat_intro_kitchens: "Heart of Your Home",
        cat_intro_bathrooms: "Design and Comfort for Your Bathroom",
        cat_intro_kids: "Functional and Fun Solutions for the Children's Room",
        cat_cta: "Discuss your project with us.",

        flourish_title: "Space for Life<br>to Flourish",
        flourish_desc: "Discover our premium solutions that give a minimalist look to your home with a touch of luxury.",

        transform_bg_text: "Ready to Create<br>Your Dream<br>Home?",
        transform_bottom_text: "Write to us<span style='margin-left: 3rem'>Or give us a call</span>",
        transform_cta_text: "Let's<br>Shop Now",

        cb_marquee: "Natural Materials • Everyday Living • Shapes • Natural Materials • Everyday Living • Shapes • ",
        cb_text_1: "If you're interested in our furniture, materials, or ongoing work, we welcome conversations around projects.",
        cb_text_2: "For trade, residential, or commercial enquiries, please reach out directly.",
        cb_btn: "Contact Us",

        mixed_title_1: "Quiet Growth: A Warm Home Shaped by Greenery and Gentle Moments",
        mixed_title_2: "Warm Layers: A Calm Dining Space for Shared Moments",
        tag_oriental: "Oriental",
        tag_natural: "Natural",
        tag_family: "Family",
        tag_calm: "Calm",
        tag_warm: "Warm",
        tag_layered: "Layered",
        tag_dining: "Dining",
        view_case: "View Case",
        
        reviews_heading: "What our customers say about our services",
        google_reviews_subtitle: "Based on verified Google reviews",
        review_upload_label: "Review Photos (max 3)",
        review_upload_drag: "Drag & drop photos here or click to select",
        btn_leave_review: "Leave a Review",
        review_placeholder_1: "\"Exceptional quality and attention to detail. The team was highly professional from the initial 3D design to the final installation.\"",
        review_name_1: "Client Name",
        review_role_1: "Sofia",
        review_placeholder_2: "\"They transformed our kitchen into a masterpiece. Functionality and aesthetics perfectly balanced.\"",
        review_name_2: "Client Name",
        review_role_2: "Plovdiv",
        review_placeholder_3: "\"Highly recommend! The custom wardrobe fits perfectly and the materials used are top notch.\"",
        review_name_3: "Client Name",
        review_role_3: "Varna",
        review_placeholder_4: "\"Great communication and flawless execution. Our living room looks like it belongs in a magazine.\"",
        review_name_4: "Client Name",
        review_role_4: "Burgas",
        
        footer_title: "Quiet, Natural, Meaningful Living",
        footer_desc: "Custom Furnitures is a lifestyle brand crafting quiet, natural furniture for everyday living.",
        footer_quick: "Quick Links",
        footer_home: "Home",
        footer_product: "Our Product",
        footer_featured: "Featured Project",
        footer_contact: "Contact",
        footer_leave_review: "Leave us a review",
        review_title: "Leave Your Review",
        review_subtitle: "Share your thoughts on our custom furniture and service",
        review_form_name: "Your Name",
        review_form_city: "City",
        review_form_rating: "Rating",
        review_form_text: "Your Review",
        review_form_submit: "Submit Review",
        review_success: "Thank you! Your review has been submitted successfully.",
        review_back_home: "Back to Home",
        footer_studio_title: "Our Studio",
        footer_studio_address: "Mladost 2, bl. 225, 1799 Sofia<br>Bulgaria",
        footer_legal: "Legal",
        footer_terms: "Terms & Conditions",
        footer_privacy: "Privacy Policy",

        // Case Studies (Example)
        case_title: "Premium Kitchen with Integrated LED Lighting",
        case_challenge: "Challenge: Optimizing a non-standard space and utilizing the maximum height.",
        case_solution: "Solution: Custom-made furniture with seamless appliance integration and smart layout.",
        case_materials: "Materials used: MDF oak veneer, Blum hardware, Italian lacquer",
        btn_case_inquire: "Inquire about a similar project",

        // Contact Page
        contact_heading: "Contact Us",
        contact_subheading: "Send us an inquiry and we will get back to you to discuss the details of your project.",
        form_name: "Full Name",
        form_phone: "Phone Number",
        form_email: "Email Address",
        form_desc: "Describe your project (room type, dimensions, specific requirements)",
        form_file: "Attach a file (sketch or photo)",
        btn_form_submit: "Send Inquiry",

        // Project Modal
        modal_btn_similar: "Request a quote for a similar project",
        modal_btn_consult: "Request a consultation",
        modal_desc_placeholder: "A brief description of the project, including details about materials and design.",
        form_autofill: "Hello, I am interested in a project similar to"
    }
};
